    print("                      ___ ")
    print("                      \\ \ ")
    print("                       \\ `\ ")
    print("    ___                 \\  \ ")
    print("   |    \                \\  `\ ")
    print("   |_____\                \    \ ")
    print("   |______\                \    `\ ")
    print("   |       \                \     \ ")
    print("   |      __\__---------------------------------._. ")
    print(" __|---~~~__o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_o_[][\__ ")
    print("|___                         /~      )                \__ ")
    print("    ~~~---..._______________/      ,/_________________/ ")
    print("                           /      / ")
    print("                          /     ,/ ")
    print("                         /     / ")
    print("                        /    ,/ ")
    print("                       /    / ")
    print("                      //  ,/ ")
    print("                     //  / ")
    print("                    // ,/ ")
    print("                   //__/ ")
    print()